#config_version=6

switches:
  # cabinet switches
  s_flipper_left:
    number:
    tags: left_flipper
  s_flipper_right:
    number:
    tags: right_flipper
  s_start:
    number:
    tags: start

  # Playfield switches
  s_bumper_left:
    number:
  s_bumper_right:
    number:
  s_left_lane:
    number:
  # For WCS Goal mode
  s_star_1:
    number:
  s_star_2:
    number:
  s_star_3:
    number:
  s_star_4:
    number:
  s_goal:
    number:


  # trough switches
  s_trough_1:
    number:
  s_trough_2:
    number:
  s_trough_3:
    number:
  s_plunger_lane:
    number:
